### ISSUE TITLE
SMS notifications

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#1017]
### Context
Currently, users of this application only receive notifications via email. 

### Problem
Challenges with deliverability damper the effectiveness of email notifications for some users.

### Solution
Introduce SMS as an additional communication channel. Stakeholders believe that SMS will have a further reach than email when it comes to volunteers who historically have not engaged via email – especially for those who already rely on SMS and/or phone for corresponding with their supervisor.

### Competitive advantage:
This will mark a truly unique feature for CASA staff and volunteers across the country, as current market solutions (there are really only two that are widely used) do not offer any form of SMS notifications. 

### Approach
This will mark the first time Ruby For Good is utilizing Twilio's services, so many of the items below under "requirements" relate to account creation and initial setup. We will be securing platform credits through a partnership with Twilio, hopefully keeping this feature forever free to stakeholders. 

A handful of the notifications below already exist in email form. The stakeholders' preference is for these to be replicated as SMS notifications, so that users can choose the combination of communication channels that works best for them. 

The initial cadence of many of the below notifications is quite conservative at the stakeholders' request. We may increase frequency (or give users the ability to customize frequency) later on. 

### Use cases (Events for which SMS can be sent)
Must-haves: 

1. Notify Supervisor (if actively assigned to a volunteer):
- When supervisor asked to reset their password #1792 
- Weekly for a shorter version of email digest  (Contains list of volunteers who have not created a case contact in the last 14 days) see #1797 

2. Notify Volunteer (if actively assigned active cases):
- To remind volunteer one week before court report due date to write court reports for active assignments #1794 
- When volunteer asked to reset their password #1792 
- 2 weeks after volunteer logged a `case_contact` as `contact_made=false`to remind them to try again. #1796 
- When a supervisor or admin generates a follow up on a case_contact associated with a volunteer's active case_assignment #1886
- When they are deactivated by an admin #1887 
- When they are reactivated by an admin #1887 
- Quarterly to remind them to connect with any `case_contact_types` they haven't made contact with in 60 days or more #1793 
- 
2. Notify Admin:
- When Admin asked to reset their password #1792 

Nice-to-have(s):
- Notify new CASA admin with invite SMS (includes details on how to log in for the first time). #1784 
- Notify new volunteers with invite SMS (includes details on how to log in for the first time). #1784 
- Notify new supervisors with invite SMS (includes details on how to log in for the first time). #1784 

### Requirements
- [x] #1785 admins can add phone numbers to all user accounts
- [x] #1786 supervisors can add and edit phone numbers to their own accounts
- [x] #1787 supervisors can add and edit phone numbers to volunteer accounts
- [x] #1788 add phone number column to system imports for supervisors
- [x] #1789 add phone number column to system imports for volunteers
- [x] #1790 add SMS opt-in to system imports containing mobile numbers
- [x] #1791 create SMS Terms & Conditions and add to site footer
- [x] #1780 Ruby For Good CASA has a Twilio account
- [x] #1781 Twilio is integrated with app for event triggered notifications
- [x] #1782 URLs in notifications are shortened
- [x] #1783 URLs in notifications are deep links when applicable
- [x] #1784 all users receive account activation notification
- [x] #1792 all users have the option to receive password reset via SMS
- [x] #1016 all users can configure their communication preferences
- [x] #1793 volunteer receives one quarterly reminder to connect with any `case_contact_types` they haven't made contact with in 60 days or more 
- [x] #1794 volunteer receives one reminder to submit their court report seven days before their court report is due
- [x] #1796 volunteer receives a "try again" reminder two weeks after logging a `case_contact` as `contact_made=false`
- [x] #1886 volunteer receives SMS to notify of follow up generated by admin or supervisor
- [x] #1887 volunteer receives SMS when account deactivated/reactivated by admin
- [x] #1797 supervisor receives one notification every two weeks alerting them of their volunteers assigned who haven't _logged_ a `case_contact` in 14 days or more
- [x] #1885 Give user the ability  to customise which SMS notifications they want to receive
- [x] #1884 Give user the ability  to enable/disable SMS notifications
- [ ] #3551

### Additional Issues

- [x] #3411 User validator should use PhoneNumberHelper for validation
- [x] #3547 Import javascript has null values on non-import pages
- [x]  #3609 Add phone number field to create supervisor and volunteer page
- [x] #3616 Send a "set your password link" with account activation SMS

**Comment by Zrrrpy** [comment]
We will be reviewing this today with stakeholders. After receiving their feedback and starting some of the RFG side of account setup, this should be ready for folks to work on!

**Comment by scottolsen** [comment]
The [noticed gem](https://github.com/excid3/noticed#twilio-sms) I used for the `Followup` notifications has Twilio support built in to it.

**Comment by compwron** [comment]
Closing for now until we get back to this

**Comment by xihai01** [comment]
@compwron @Zrrrpy just to confirm, can a volunteer edit/add their own phone numbers?

**Comment by xihai01** [comment]
@compwron it seems SMS right now is used to send notifications to users from the app. Does CASA foresee the need for users to reply to SMS messages in the future?
