### ISSUE TITLE
Add route to Emancipation Checklist from sidebar for volunteers

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1068]
dependent on #792

AS a **volunteer**,
IF I have an active `transition_aged_youth` case assignment,
I WANT to see the text "Emancipation Checklist" in the left sidebar,
SO THAT I can click on it and see Emancipation Checklists for my active `transition_aged_youth` case assignment(s). 

**Acceptance Criteria**
- [x] Text: "Emancipation Checklist" displays in left sidebar for volunteer users.
- [x] "Emancipation Checklist" is clickable. 
- [ ] Clicking it takes user to Emancipation Checklists per `casa_case` (See how `case_contacts` are handled for volunteers with more than one active case assignment.)

**Comment by FireLemons** [comment]
May I have this assigned?

**Comment by FireLemons** [comment]
I'm unassigning myself because I'd like to work on #792
