### ISSUE TITLE
make emancipation checklist dynamic

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1494]
As a **volunteer** (or admin/supervisor, but mostly volunteer),
when I am using my Emancipation Checklist,
I want to only see items associated with each header category _after_ I check the box associated with that header category,
so that my checklist is more focused and less cluttered. 

### How it works now
Everything displays all the time, regardless of user input. This makes the list long and overwhelming.

### How it should work instead
If the box next to the header category is unchecked, only the header displays.
- [ ] **Youth has income to achieve self sufficiency.**

If the box next to the header category is checked, then the items associated with that category also display.
- [x] **Youth has income to achieve self sufficiency.**
   - [ ] Employment
   - [ ] Public Benefits/TCA
   - [ ] SSI 
   - [ ] SSDI
   - [ ] Inheritance/survivors benefits.

This should also apply to categories with _dropdown menus._ The items in the dropdown menu should function just like the checkbox items detailed above. (The "no" option currently in some dropdown menus _can be removed._ Not checking the box next to an item will serve as the equivalent of "no".)

**Comment by FireLemons** [comment]
What does it mean for a category to be checked but none of the options selected?

**Comment by Zrrrpy** [comment]
here's an example of a category that is checked with no corresponding items or "options" beneath it selected, @FireLemons:

- [ ] Youth has income to achieve self sufficiency.
   - [ ] Employment
   - [ ] Public Benefits/TCA
   - [ ] SSI
   - [ ] Inheritance/survivor benefits.
   
So in this case, the items beneath the category _should_ display _because_ their corresponding category is checked. 
   
If a volunteer checks the category but no corresponding items, it is likely the youth has fulfilled the requirements of this category, but not in a way that is listed. (This would be the equivalent of an "other" box, which we tend to avoid because it weakens stats for CASA administrators.)

Let me know if you have any more q's about this! And thank you for working on it 🙌🏼
