### ISSUE TITLE
Feedback loop between Volunteers & Supervisors

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1495]
### Context
This application seeks to replace outdated tactics for managing volunteers currently used by stakeholders with a more unified, efficient tool suite. 

One of those tactics involves the way volunteers and supervisors relay information in regards to `case_contacts`.  Currently, supervisors utilize a variety of communication tools (SMS, email, phone) to tell a volunteer that they need to follow up with their `case` or with a contact associated with their `case`. 

### Approach
The requirements below relate to new features and improvements which will:
- move these communications on-platform
- streamline these communications by reducing back & forth
- provide a more holistic view of outstanding items that require a volunteer or supervisor's attention
- close the loop on completed items

### Requirements
- [x] #1496 all users can flag a `case_contact` that requires followup
- [x] #1497 followups generated by `supervisors` and `admins` are distinguishable from those generated by `volunteers`
- [x] #1506 open followups can be closed by any user
- [x] #1507 `supervisors` and `admins` receive notifications when a `volunteer` closes a followup generated by that `supervisor` or `admin`
- [x] #1508 `volunteers` receive notifications when a followup has been generated for them by a `supervisor` or `admin`

**Comment by scottolsen** [comment]
@Zrrrpy I'm curious if any of the below are valid scenarios?

- A case contact to have multiple followups open at once? Possibly a volunteer and admin both mark it?
- After a followup is resolved, should that case contact every allow another followup?

**Comment by Zrrrpy** [comment]
Thank you for working on this, @scottolsen! 🙏🏼  Apologies for the delayed reply.
Once a followup is added to a case contact, it should not be possible to add another one – even across user types (volunteer/supervisor/admin). 
Yes, new followups should be able to be added to a case contact after an outstanding followup is resolved.
