### ISSUE TITLE
change meta data that appears under header on case_contact cards

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1500]
### How it works now
The metadata that appears under headers on page cards is not the neatest and is confusing to read. 

### How it should work instead
`case_contact` cards should look like this example (example does not include notes):

**Placement, Social Services, Health**
Foster Parent, Social Worker, Mental Health Therapist
June 14, 2020 | 4 hours | Contact Made | 40 miles | Reimbursement

### Acceptance Criteria
- [ ] headers in `case_contact` cards reflect the case contact type groups selected in the `case_contact`
- [ ] line underneath header lists the `case_contact_types` selected
- [ ] line underneath that lists (in this order): 
   - [ ] date
   - [ ] duration 
   - [ ] contact made/not made 
   - [ ] miles driven (blank if 0)
   - [ ] reimbursement (blank if no)
