### ISSUE TITLE
Court Details

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#1730]
### Context
Different CASA chapters include slightly different details in their court reports. We are expanding the offering of court details available in order to better accommodate new platform tenants. (Court details are associated with a `case`, and get included in court reports generated by volunteers assigned to a `case`.)

### Approach
The requirements below focus on court mandates (details which a new platform tenant includes in their court reports) and on changes to past court dates & details.

### Requirements
- [x] #1731 add court mandates to Edit CASA Case page
- [x] #1733 court mandates can be edited/removed
- [x] #1734 add implementation status to Edit CASA Case page
- [x] #1735 court mandates and status are viewable on CASA Case Details page
- [x] #1736 if `case` has court mandates, add to court report
- [x] #1739 past court details are associated with past court dates
- [x] #1741 generate past court reports associated with past court dates

**Comment by r-sierra** [comment]
@Zrrrpy should this issue be closed? All tasks are done

**Comment by compwron** [comment]
Correct, this issue is an epic and the entire epic has been done. :)
