### ISSUE TITLE
Create A Follow Up Button on Emancipation Checklist

### ISSUE THREAD

**Issue by CovenantHuman** [rubyforgood/casa#2699]
**What type(s) of user does this feature affect?**
 - volunteers
 - supervisors
 - admins

**Description**
Add a Follow-up Button (now called a Make Reminder) like the one displayed on case contacts to each individual section of the Emancipation Checklist. This Button should work in the same way as it does on case contacts, where it offers the individual requesting the follow-up a textbox to elaborate on the follow-up required and sends a notification to the volunteer in charge of the case. 

_note on possible addition_: include some sort of reference to checklist reminders in the EmancipationChecklistReminderNotification, if this doesn't exist. Could be a separate pr but maybe if it's just a small text change it would be okay here. 
- for case_details add option to edit the reminder and/or see what it was somewhere. this would definitely be a new issue. or see reminder in place where it was made instead of the in app message.
- email notification for reminder followups? v2: option for volunteer creator to skip email. v3 creator can schedule email reminder. 

**Screenshots of current behavior, if any**  
Follow-up behavior on a case-contact as a guide:
Go to route: `/casa_cases/:id` e.g. `casa_cases/cina-xx-xxxx`
`_followup.html.erb` | `render "case_contacts/followup"`
Click 'Make Reminder' button
A reminder will send a notification to the creator of the case_contact.

![Follow up Behavior](https://github.com/rubyforgood/casa/assets/17803351/4255c6fa-a94c-4e34-a54d-64dd5415803a)
![Follow up Behavior](https://github.com/rubyforgood/casa/assets/17803351/e30ce2d6-ba46-4450-a641-22e60966f9af)

_QA Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

## This will be a multi-pr feature. 

**Existing gem(s), file(s) needing updating, changing or deleting**

- [ ] followup.rb
- [ ] followups_controller.rb
- [ ] routes.rb
- [ ] followup_notification.rb
- [ ] followup_resolved_notification.rb
- [ ] _followup.html.erb
- [ ] _case_contact.html.erb
- [ ] case_contact.js (jquery)
- [ ] case_contact.rb
- [ ] sms.rb maybe?
- [ ] application_policy.rb?
- [ ] followup_export_csv_service.rb
- [ ] spec/factories/followups.rb
- [ ] spec/models/case_contact_spec.rb
- [ ] spec/models/followup_spec.rb
- [ ] spec/requests/case_contacts_spec.rb
- [ ] spec/requests/followups_spec.rb
- [ ] spec/services/followup_export_csv_service_spec.rb
- [ ] spec/system/case_contacts/followups/create_spec.rb (may not need to change this by adding .followups to case_contact model. Do need to check this file. 
- [ ] spec/system/case_contacts/followups/resolve_spec.rb
- [ ] index_spec.rb
- [ ] tests for the copying migration task

**New file(s) needing creating**
- [x] migration file to create polymorphic columns
- [x] a task to migrate case contact id column to followupable id and type columns. 
- [ ] possible extra tests (may be handled by updates to existing tests)

possible breakdown

PR 1: 
- [x] migration file to create polymorphic columns
- [x] task possibly with AfterParty gem to copy followup data to polymorphic columns
- [x] testing for ^^

PR2: this could be broken into multiple PR's to be safer. 
1. all the file updates
 - re-org file nesting to extract from case_contact
 - pain point: deal with the jquery Swal alerts that actually handle the POST to create followup. will try to remove that part
3. testing updates

PR3: 
- remove case_contact_id column
- remove backwards compatibility

1. Create a new column
2. Write to both columns
4. Backfill data from the old column to the new column
5. Move reads from the old column to the new column
6. Stop writing to the old column
7. Drop the old column

**Comment by compwron** [comment]
> Hi, I was thinking about picking this issue, and I found out that the Emancipation Checklist page is very different from the case contacts one. There's no space for a follow up button there unless I open the tab: ![Screenshot 2021-10-08 at 15 39 03](https://user-images.githubusercontent.com/11601901/136576244-4d29dc51-a1e1-42f8-8d53-0a7c81621c5c.png)
> 
> Do you have any designs or sketches on how the button should look on the page?

Hi! Sorry for the late reply- we don't have a mockup, please just use your judgement on spacing.

**Comment by davetheknave8** [comment]
Hey - haven't seen much activity on this one for a few years. I'll take a crack at it.

**Comment by acasarsa** [comment]
This doesn't seem like it is still being worked on. I'm going to take a stab at it. It is my first issue but I think I can do this one.

**Comment by acasarsa** [comment]
I have some notes on what may need to be changed to get this feature implemented. 
Currently, the Followup model is intricately linked with CaseContact, limiting its applicability to other entities such as items in the emancipation checklist. To extend the functionality of followups to broader use cases, several architectural changes are needed:

1. **Generalize the Followup Model:** The Followup model could be reworked to allow associations with entities beyond CaseContact. Implementing a polymorphic association is a viable strategy, enabling a Followup to be linked with any model, such as CasaCase or a specific Volunteer (User). This would enhance its flexibility and reuse across different contexts.
2. **Update Controllers for Reusability**: The current controller and its organizational structure are tailored specifically to CaseContact followups. We'd need to either adapt this controller to handle followups for various entities through a more generic approach or create a new controller dedicated to managing followups for cases and emancipation checklist items. This rework will involve deciding on a unified or context-specific controller strategy to maintain clean and maintainable code. *it should be noted at the moment followup_controller is within a case_contact dir. We can investigate whether keeping that structure vs a single controller is best. Perhaps using controller concerns would be helpful to avoid reaping logic. 
3. **Revise Followup Routing Strategy:** Introducing a more versatile routing strategy or reworking the existing routes to accommodate the creation of followups across different entities is needed. 
4. **Add Flexiblility to Notification System**: Adding flexibility here would be great, this could be a pr inself really. But for this issue the main thing is to figure out who should be notified about the checklist followup. 
5. **Update to javascript/jquery files**: currently these capture a case_contact_id to make a POST request for creating a CaseContact followup. Could generalize this script to work for different id's or make a separate one. 

!! *There may be other areas but these were the ones that I've noticed so far.

**Comment by compwron** [comment]
Mallory and I talked to stakeholder Jocie about this today - 
Probably still wanted, there may be other ways to solve
Primarily asked for by a CASA other than Jocie's - let's dig out who it was if possible - maybe email stakeholders to ask? 
Jocie: There were talks about adding emancipation items to the end of a case contact... that might solve the problem? If volunteers were prompted every time they did a case contact?

**Comment by acasarsa** [comment]
@compwron adding emancipation items to the `_case_contact.html.erb` would make this feature substantially easier to implement. The tricky but workable part would be changing how there can only be 1 requested followup at a time.

**Comment by acasarsa** [comment]
Part 1 of this epic is complete.

**Comment by compwron** [comment]
I am closing this as old. We may bring it back in a different form.

**Comment by acasarsa** [comment]
assigning for file list reference while i work on the rest of the polymorphic migration process pr's. hoping to get part 2 started this weekend.
