### ISSUE TITLE
user dashboard for All CASA Admin

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#628]
Part of epic #527

**What type of user is this for? [admin/volunteer/supervisor/all or All CASA Admin]**
All CASA Admin

**Where does/should this occur?**
This should be the page the All CASA Admin lands on immediately after logging in, that serves as their main interface. (See other user dashboards for examples. <a href="https://github.com/rubyforgood/casa/blob/master/db/seeds.rb">Login information here.</a>

**Description**

**1.** 

After logging in, the All CASA Admin should land on a user dashboard where they will be able to take the following actions:

- [ ] create `casa_org` accounts (implemented in #687)
- [ ] create `casa_admin` accounts (implemented in #686)

And view the following information:

- [ ] each `casa_admin` account associated with a `casa_org` (implemented in #685)

It should look something like this:

---

### CASA Organizations

| Name | Created on | Admins | Link |
| --- | --- | --- | --- | 
| Some CASA | 03/29/20 | admin1@somecasa.org, admin2@somecasa.org | [View](#) |
| Another CASA | 05/19/20 | admin1@anothercasa.org | [View](#) |

---

**2.** 

There will eventually be two buttons to the right of the Section header:

- [ ] New Org (implemented in #687)
- [ ] New Admin (implemented in #686)

**Screenshots**
Volunteer dashboard layout, for reference.           
![Screen Shot 2020-08-31 at 6 04 24 PM (2)](https://user-images.githubusercontent.com/62810851/91783277-8bc7f700-ebb4-11ea-95d9-07f70f2d81cf.png)

Relates to issue: #627
