### ISSUE TITLE
emancipation checklist 

### ISSUE THREAD

**Issue by compwron** [rubyforgood/casa#792]
AS a **volunteer**, 
IF I have an active `transition_aged_youth` `case_assignment`,
I WANT to access an Emancipation Checklist,
SO THAT I am better equipped to prepare my `casa_case` for emancipation.

**Acceptance Criteria**
- [ ] On the CASA Case Details page, there is a button (next to "Edit Case Details") with the text "Emancipation".
- [ ] This button directs to the Emancipation Checklist (see below).
- [ ] Volunteer can check items off the checklist. 
- [ ] Volunteer can uncheck items.
- [ ] Changes are saved immediately as volunteer checks and unchecks items. 
- [ ] Admins and supervisors have the same view/edit permissions as volunteers.

**Emancipation Checklist**

- [ ] **Youth has housing.** 
- [ ] With friend 
- [ ] With relative 
- [ ] With former foster parent 
- [ ] Subsidized (e.g., FUP, Future Bridges, adult services) 
- [ ] Independently (e.g., renting own apartment or room) 

- [ ] **Youth has income to achieve self-sufficiency.**
- [ ] Employment 
- [ ] Public benefits/TCA 
- [ ] SSI 
- [ ] SSDI 
- [ ] Inheritance/survivors benefits 

- [ ] **Youth has completed a budget.** 

- [ ] **Youth is employed.**
- [ ] Part-time job 
- [ ] Full-time job 
- [ ] Apprenticeship or paid internship 
- [ ] Self-employed 

- [ ] **Youth is attending an educational or vocational program.**
- [ ] High school 
- [ ] Post-secondary/college 
- [ ] Vocational 
- [ ] GED program 

- [ ] **Youth has a high school diploma or equivalency.**
- [ ] Traditional
- [ ] Out of school program 
- [ ] GED 

- [ ] **Youth has medical insurance.**
- [ ] Has medical insurance card 
- [ ] Knows his/her/their primary care entity 
- [ ] Knows how to continue insurance coverage 
- [ ] Knows that dental insurance ends at age 21 
- [ ] Has plan for dental care 

- [ ] **Youth can identify permanent family and/or adult connections.**

- [ ] **Youth is accessing community activities.**
- [ ] Arts activities (e.g., singing, dancing, theater) 
- [ ] Religious affiliations (e.g., church, mosque) 
- [ ] Athletics/team sports 
- [ ] Other

- [ ] **Youth has all identifying documents.**
- [ ] Birth certificate (original or certified copy)
- [ ] Social security card
- [ ] Learner's permit
- [ ] Driver's license
- [ ] Immigration documents
- [ ] State Identification card

- [ ] **Youth has access to transportation.**
- [ ] Vehicle
- [ ] Public transportation

- [ ] **Youth has been or is involved in past or current juvenile cases.**
- [ ] All juvenile issues have been resolved.
- [ ] All eligible juvenile records have been expunged.

- [ ] **Youth has been or is involved in past or current adult criminal cases.**
- [ ] All adult criminal cases have been resolved.
- [ ] All eligible adult criminal records have been expunged.

- [ ] **Youth has been or is involved in civil or family cases.**
- [ ] All civil or family cases have been resolved.

- [ ] **Youth has a bank account in good standing.**
- [ ] Checking
- [ ] Savings

- [ ] **Youth has obtained a copy of his/her/their credit report.**
- [ ] An adult has reviewed the credit report with Youth.
- [ ] Issues or concerns 

- [ ] **Youth can identify his/her/their core values.**

- [ ] **Youth has completed the Ansell Casey Assessment.**
- [ ] Threshold for self-sufficiency was met.

**Comment by FireLemons** [comment]
May I have this assigned?

**Comment by compwron** [comment]
@FireLemons How is it going? :)

**Comment by FireLemons** [comment]
@compwron Pretty good. I probably won't finish by the 31st. I have this on the front end. 
![image](https://user-images.githubusercontent.com/8918762/97648406-a7b80f80-1a22-11eb-9688-8b277ee09a18.png)
I have this project to keep track https://github.com/FireLemons/casa/projects/1

**Comment by compwron** [comment]
@FireLemons it's looking great! I am excited :)

**Comment by Zrrrpy** [comment]
Hey @FireLemons! It's been a minute since we've heard from you so we're going to unassign this and put this into the To-do column. We'd love to have you back, though! Please feel free to drop back in whenever you're ready. :)

**Comment by compwron** [comment]
Hi @FireLemons ! Now I see that you are actively developing on this! It is looking super great and we are very excited. I'm sorry that you were unassigned from it. We value your work 💖✨

I have opened a "draft" PR for your branch just to keep it visible. Feel free to close this PR and make a new one, or use/edit it - whatever works best for you. If you have any permissions troubles please comment here or in slack and we will make sure that you have what you need :)
