### ISSUE TITLE
Convert form page views to card view

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#822]
As a user [all user types: volunteer, admin, supervisor] I want to click on a view/create/edit item in the menu sidebar,
so a new form route renders.

**How does it work now?**
Clicking on any view/create/edit opens a new page.

**How should it work?**
Clicking on any view/create/edit button so a new form route renders.

**Which pages / forms should this apply to?**
All, including:
- [ ] #837 View / Create / Edit `casa_case`
- [ ] #829 View / Create / Edit `case_contacts`
- [ ] #835 View / Create / Edit `volunteers`
- [ ] #841 View / Create / Edit `supervisors`
- [ ] #844 View / Create / Edit `admins`
- [ ] #832 Edit user profile
- [ ] #846  Edit CASA Org

**Permissions Changes Required?**
None

**Launch Plan**
Roll out to Admins and Supervisors first, then all users. 

**Acceptance Criteria**
Forms are accessible by the new blue sidebar menu.
Forms expand on the same page when opened.
Forms do not open in a new page.

Mockups:
[casa-new-contact.pdf](https://github.com/rubyforgood/casa/files/5270195/casa-new-contact.pdf)
