### ISSUE TITLE
Court Reports

### ISSUE THREAD

**Issue by Zrrrpy** [rubyforgood/casa#880]
As a **Supervisor**, 
I want to add the next _court date_ and _court report due date_ per `casa_case` AND be able to mark a `volunteer`'s associated _court report_ submission as _in review_ or _complete_,
so that I can more easily track required volunteer activities leading up to their next court appearance with their `casa_case`. 

As a **Volunteer**,
I want to see my assigned `casa_case`'s next _court date_ and associated _court report due date_ AND see the status of my _court report_ after submitting it,
so that I know when to prepare and submit my _court report_ AND know what stage in the review process it is in. 

I _also_ want to generate a court report auto-filled with select details,
SO that I can download it and fill out remaining details before submitting it to my supervisor for review.

As an **Admin**, 
I want to see a `casa_case`'s next _court date_ and the associated volunteer's _court report due date_ AND whether or not their _court report_ has been submitted,
so that I can track progress and know to assist their supervisor assignment if the volunteer is not on track to meeting associated deadlines. 

**Acceptance Criteria**
- [x] #807 `supervisor` and `admin` can add next court date per `casa_case`.
- [x] #927 `supervisor` and `admin` can associate a `hearing_type` and `judge_name` with a `court_date`
- [x] #928 `admin` can customize `hearing_types` for their `casa_org`
- [x] #929 `admin` can customize `judge_names` for their `casa_org`
- [x] #1153 `judge_names` only display after `admin` adds them to a `casa_org` instance
- [x] #808 `supervisor` and `admin` can add court report due date per `casa_case`.
- [x] #805 Past court dates appear with `casa_case` details.
- [x] #619 `volunteer` can adjust court report submission status from `false` to `true`
- [x] #882 court report submission status updates automatically
- [x] #806 `supervisor` and `admin` can edit court report status 
- [x] #881 Next Court Date clears after court date has passed
- [x] #922 Volunteers can generate a court report for transition aged youth 
- [x] #1064 Volunteers can generate a court report for non-transition aged youth 
- [x] #923 Volunteers can navigate to "Generate Court Report"

**Comment by littleforest** [comment]
@Zrrrpy does this make sense for the database schema:

Table: court_dates
Fields:

| Field | Type |
| :----- | :------ |
| court_date | date |
| court_report_submitted_at | date |
| court_report_status | enum (string) |
| court_report_due_date | date |

**Comment by Zrrrpy** [comment]
This looks good @littleforest!

**Comment by acrosman** [comment]
I'm a _Guardian ad Litem_ in another state (more or less interchangeable for Maryland CASAs), but new to this project, I'm looking through issues for places to engage productively so if I'm out of line please feel free to tell me. I think the data structure here is a good start but as a volunteer in similar roles it misses two pieces of information I always want: the type of hearing (it matters for report content) and the expected judge (here this can change last minute, but can be helpful to know when appearing). 

I would also expect the court_date field to be a datetime not just a date. It is not as useful as one would generally like -- although has been more useful during the current move to virtual hearings when the court is staying much more on a fixed schedule.

So I suggest the following revision to the above table.

Field | Type
-- | --
casa_case | reference
court_date | datetime
hearing_type | enum (string)*
judge_name | string
court_report_submitted_at | date
court_report_status | enum (string)
court_report_due_date | date

* Ideally this could be adjusted per-instance as different states likely have different options and names for the hearing types.

**Comment by Zrrrpy** [comment]
I approve of these additions to the table. They will help with us pre-filling more data for court reports (#922). I'm fine with datetime vs date. (I think this will mostly be useful to volunteers.)

And welcome @acrosman 👋  I'm a former San Francisco County CASA.

**Comment by littleforest** [comment]
Thanks @acrosman I think `court_report_submitted_at` should also get changed to a timestamp:

```
Field | Type
-- | --
casa_case | reference
court_date | datetime
hearing_type | enum (string)*
judge_name | string
court_report_submitted_at | datetime
court_report_status | enum (string)
court_report_due_date | date
```

Also, good point about hearing type. This could actually be a table in its own right and be linked to a `casa_org` so it could be customized for each organization.

**Comment by Zrrrpy** [comment]
^^ yes, let's do this @littleforest!

@acrosman can you send a short list of hearing types common to your locality? I will also email PG to get their short list so I can narrow down defaults and then give admins the ability to add/edit/show/hide `hearing_types`. 

We can set these up the same way we've built out `contact_types` so they can be associated with a `casa_org` _and_ a `casa_case`.

**Comment by acrosman** [comment]
For Hearings in SC we have:

- Emergency Protective Custody (EPC)
- Probably Cause
- Merits
- Judaical Review
- Permanency Planning
- Termination of Parental Rights (TPR)
- Adoption Finalization

GALs rarely attend EPC and Probably Cause (usually happens before we are assigned), but we are supposed to be in place in time to form an opinion for Merits. We attend a lot of PP and JR hearings.

**Comment by acrosman** [comment]
I posted this on #928 but I'll add it here too:

Looks like Maryland needs at least:

- emergency hearing 
- trial on the merits 
- scheduling conference
- uncontested hearing
- pendente lite hearing
- pretrial conference
- other

Source: https://www.courts.state.md.us/sites/default/files/court-forms/family/forms/ccdr059.pdf/ccdr059.pdf
